{
  "blade_phone" = {
    id = "C5IITCD-SC36RFN-CBBVCY2-7PKGJQZ-2CEVD3Z-GEIZGSJ-TA5CIV4-MHBDMAB";
  };
  "bladetop" = {
    id = "ZX3NYQZ-X564MUA-CX67FTI-VR2KPUR-QO5VXLV-HO3XOAE-4NZWFXN-AVXMYAC";
  };
}
